api_login_check:
    path: /api/login_check

variations:
    type: annotation
    resource: App\Controller\VariationController
    prefix: api

products:
    type: annotation
    resource: App\Controller\ProductController
    prefix: api

product_rating:
    type: annotation
    resource: App\Controller\ProductRatingController
    prefix: api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }


    
    