variations:
    type: annotation
    resource: App\Controller\VariationController
    prefix: api

products:
    type: annotation
    resource: App\Controller\ProductController
    prefix: api


    
    